### ISSUE TITLE
FIX: search placeholder & read more button

### ISSUE THREAD

**Issue by ItzKazuki** [ItzKazuki/School-web#22]
ubah placeholder ini
![image](https://github.com/ItzKazuki/School-web/assets/79141593/f53ee8a1-dd16-4555-bb56-9a8946e716a1)

menjadi text-brown-800

dan ini

![image](https://github.com/ItzKazuki/School-web/assets/79141593/9f0cba64-0120-4aa3-90db-ba7565dc34ae)

kira kira jadi button atau jadi text yang bisa di pencet ya dika?

**Comment by 0rcaaa** [comment]
gw maunya button read morenya itu jadi animasi
itu sebernya cuman prototep doang, ntr mau gw jadiin 2 garis ngadep ke bawah

**Comment by 0rcaaa** [comment]
pace holdernya gw bingung jga jujur

**Comment by ItzKazuki** [comment]
trs jd ini 
![image](https://github.com/ItzKazuki/School-web/assets/79141593/3606f224-90d3-4a6d-af18-ee7a2c4eb5f8)
bagus nya pas di atas warnanya brown-800 pas di bawah di ubah jadi brown-500 ya ga si?

**Comment by 0rcaaa** [comment]
itu fotonya ntr gw edit biar gk ad tulisan2 nya

**Comment by 0rcaaa** [comment]
tpi klo di jadiin 800 dia ntr nyati ama background klo udh masuk ke about

**Comment by 0rcaaa** [comment]
lu bisa ubah warna fontnnya pas dia masuk ke about kgk?

**Comment by 0rcaaa** [comment]
kok gw malah ngulang omongan lu si _-

**Comment by ItzKazuki** [comment]
> tpi klo di jadiin 800 dia ntr nyati ama background klo udh masuk ke about

nanti di set balik pas di bawah ganti text ny jadi brown-500



> pace holdernya gw bingung jga jujur

pake placeholder-brown-800 bisa dika. tapi yang kelap kelip pas di pencet itu gmn anjir gantinya

**Comment by ItzKazuki** [comment]
![Uploading image.png…]()
annoying bet anjir

**Comment by 0rcaaa** [comment]
yg kelap kelip emang bisa jga? seinget gw gk bisa

**Comment by ItzKazuki** [comment]
> yg kelap kelip emang bisa jga? seinget gw gk bisa

waktu itu gw liat kontent ada yang ngubah warna nya anjir tp lupa

**Comment by 0rcaaa** [comment]
bntr gw rescearch

**Comment by 0rcaaa** [comment]
dia keknya nyatu sm warna font dh

**Comment by 0rcaaa** [comment]
iya nyatu nu ama font nu

**Comment by ItzKazuki** [comment]
> dia keknya nyatu sm warna font dh

bntr gw cek

**Comment by ItzKazuki** [comment]
no, ga ngaruh

**Comment by 0rcaaa** [comment]
lah di gw ngaruh

**Comment by 0rcaaa** [comment]
ni gw push

**Comment by ItzKazuki** [comment]
fix ini ga sih?

![image](https://github.com/ItzKazuki/School-web/assets/79141593/7430875a-8e39-49c3-adf0-ecbb40d1ab43)

![image](https://github.com/ItzKazuki/School-web/assets/79141593/8ac05b38-5e98-42dd-8875-b548b4de7916)

![image](https://github.com/ItzKazuki/School-web/assets/79141593/bcff684b-beae-4279-b79a-1c951a6f699b)

**Comment by 0rcaaa** [comment]
nah iya
kosong bener njir. kasih tulisan exentwo gk sih?  tpi pas dia sampe di about

**Comment by ItzKazuki** [comment]
hah kosong gmn, coba ss

**Comment by 0rcaaa** [comment]
gk navbarnya mksd gw, pas di andori dia kosng bgt tengahnya

**Comment by 0rcaaa** [comment]
lu mau fix apa lagi emang?

**Comment by ItzKazuki** [comment]
> lu mau fix apa lagi emang?

ga ada lagi sih

**Comment by ItzKazuki** [comment]
> gk navbarnya mksd gw, pas di andori dia kosng bgt tengahnya

eh psti gr gr ini
![image](https://github.com/ItzKazuki/School-web/assets/79141593/a5101ebb-c848-4ab1-82cf-d06a52fcbc50)

**Comment by 0rcaaa** [comment]
iyk

**Comment by 0rcaaa** [comment]
gw dh commit kok tdi lu pull aj

**Comment by ItzKazuki** [comment]
kalo pake tailwind kek gini
![image](https://github.com/ItzKazuki/School-web/assets/79141593/3d5cb9ce-1f47-4195-8f42-58ec36139144)

di commit ini https://github.com/ItzKazuki/School-web/commit/62901f97e73c2bbd4d347a79af481ed2360e63a1
sama ini https://github.com/ItzKazuki/School-web/commit/aff063be3a542aa1ae3f3bf7303bfd599b740a59

**Comment by ItzKazuki** [comment]
u pull aja dari gweh soalny gw nambahin filtur baru

**Comment by ItzKazuki** [comment]
bntr gw bikin PR ny

**Comment by 0rcaaa** [comment]
![image](https://github.com/ItzKazuki/School-web/assets/140957045/7edfefcb-7004-40dc-ba4a-ff6d72f3c2bd)
baru sadar ojan ngepak _-

**Comment by ItzKazuki** [comment]
> ![image](https://private-user-images.githubusercontent.com/140957045/309565862-7edfefcb-7004-40dc-ba4a-ff6d72f3c2bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODQ5NjQsIm5iZiI6MTcwOTQ4NDY2NCwicGF0aCI6Ii8xNDA5NTcwNDUvMzA5NTY1ODYyLTdlZGZlZmNiLTcwMDQtNDBkYy1iYTRhLWZmNmQ3MmYzYzJiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxNjUxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjVjZjNhMjQyYTAyZWZiNDk0MzI4NThkMzdhYWVjNGNkZGFiMzEwMTRmMDQxZjI1Yzg5OTk4MzMzM2UxMmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-ld53Y-IoB8WYejuPLqR4K_OnTr6F1fQ-bJk05sa9iw) baru sadar ojan ngepak _-

aowkoaowkaow

**Comment by ItzKazuki** [comment]
ada lagi ga ya yang harus di fix????????

**Comment by 0rcaaa** [comment]
> nah iya kosong bener njir. kasih tulisan exentwo gk sih? tpi pas dia sampe di about

ini bisa kgk nu

**Comment by ItzKazuki** [comment]
eh ini
![image](https://github.com/ItzKazuki/School-web/assets/79141593/f1d997e6-2fe0-4403-a39e-c17033e5a91a)
![image](https://github.com/ItzKazuki/School-web/assets/79141593/014a9740-6aec-4ba4-88d7-8ff6fc524729)
dia terlalu mepet gasih?

**Comment by 0rcaaa** [comment]
jadi pas navbarnya di section about sampe seterusnya di tampilan andro di tengah navbarnya bakal muncul tulisan exentwo

**Comment by 0rcaaa** [comment]
> eh ini ![image](https://private-user-images.githubusercontent.com/79141593/309566062-f1d997e6-2fe0-4403-a39e-c17033e5a91a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODUxMzEsIm5iZiI6MTcwOTQ4NDgzMSwicGF0aCI6Ii83OTE0MTU5My8zMDk1NjYwNjItZjFkOTk3ZTYtMmZlMC00NDAzLWEzOWUtYzE3MDMzZTVhOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE2NTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYmI4NmVhYmM5MWIxODY2NDMzYTEwZGQ2NzkyZDk5ZTk1MThiMjdmNmVmNDM5ZjMyYTEwN2E3OGQ0NTU2MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X0TzDrKX0_XbOCairHB6kGJZ1uj9nWpWTwUEsS5r1HA) ![image](https://private-user-images.githubusercontent.com/79141593/309566092-014a9740-6aec-4ba4-88d7-8ff6fc524729.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODUxMzEsIm5iZiI6MTcwOTQ4NDgzMSwicGF0aCI6Ii83OTE0MTU5My8zMDk1NjYwOTItMDE0YTk3NDAtNmFlYy00YmE0LTg4ZDctOGZmNmZjNTI0NzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE2NTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZGFhMTdiZmVjNGY3Y2NjNmM0YTQ5NGRjNjliYmVmYTFmNGM5MGRmNjkyMGE4OWVhNGU3ZWI4Y2RmZDJlNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cWCfeLeIwDsxqp562aiAIADMd8427JTmS38T04shd0U) dia terlalu mepet gasih?

ah enggak ah, pas bagi gw

**Comment by ItzKazuki** [comment]
> > nah iya kosong bener njir. kasih tulisan exentwo gk sih? tpi pas dia sampe di about
> 
> ini bisa kgk nu

![image](https://github.com/ItzKazuki/School-web/assets/79141593/d752cb61-bb54-49eb-aac8-f6e8e97ce146)
bikin ini text ketengah aja ga si kalo di android???

**Comment by ItzKazuki** [comment]
> > eh ini ![image](https://private-user-images.githubusercontent.com/79141593/309566062-f1d997e6-2fe0-4403-a39e-c17033e5a91a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODUxMzEsIm5iZiI6MTcwOTQ4NDgzMSwicGF0aCI6Ii83OTE0MTU5My8zMDk1NjYwNjItZjFkOTk3ZTYtMmZlMC00NDAzLWEzOWUtYzE3MDMzZTVhOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE2NTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYmI4NmVhYmM5MWIxODY2NDMzYTEwZGQ2NzkyZDk5ZTk1MThiMjdmNmVmNDM5ZjMyYTEwN2E3OGQ0NTU2MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X0TzDrKX0_XbOCairHB6kGJZ1uj9nWpWTwUEsS5r1HA) ![image](https://private-user-images.githubusercontent.com/79141593/309566092-014a9740-6aec-4ba4-88d7-8ff6fc524729.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODUxMzEsIm5iZiI6MTcwOTQ4NDgzMSwicGF0aCI6Ii83OTE0MTU5My8zMDk1NjYwOTItMDE0YTk3NDAtNmFlYy00YmE0LTg4ZDctOGZmNmZjNTI0NzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE2NTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZGFhMTdiZmVjNGY3Y2NjNmM0YTQ5NGRjNjliYmVmYTFmNGM5MGRmNjkyMGE4OWVhNGU3ZWI4Y2RmZDJlNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cWCfeLeIwDsxqp562aiAIADMd8427JTmS38T04shd0U) dia terlalu mepet gasih?
> 
> ah enggak ah, pas bagi gw

okokkokoko

**Comment by 0rcaaa** [comment]
kita gk nyari riviewer aj buat web kita?

**Comment by 0rcaaa** [comment]
> > > nah iya kosong bener njir. kasih tulisan exentwo gk sih? tpi pas dia sampe di about
> > 
> > 
> > ini bisa kgk nu
> 
> ![image](https://private-user-images.githubusercontent.com/79141593/309566184-d752cb61-bb54-49eb-aac8-f6e8e97ce146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODUyNTMsIm5iZiI6MTcwOTQ4NDk1MywicGF0aCI6Ii83OTE0MTU5My8zMDk1NjYxODQtZDc1MmNiNjEtYmI1NC00OWViLWFhYzgtZjZlOGU5N2NlMTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE2NTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MzFhODQxMGNmMWQ3YzczM2FkMWQ1MGY1OWNhOTQ0M2Y1NzU2NDg1ODE2MWY3MGNmYjg1NTQ1NTcyZjI1YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hzQuI7EEmcp3dTMTy8mQdNMF3B0Ix6noT9AUrEkdVKw) bikin ini text ketengah aja ga si kalo di android???

boleh si

**Comment by ItzKazuki** [comment]
> kita gk nyari riviewer aj buat web kita?

siapaaaa?? ntr pagi coba tanya dah. kita emng butuh sih biar bisa review.

**Comment by ItzKazuki** [comment]
> jadi pas navbarnya di section about sampe seterusnya di tampilan andro di tengah navbarnya bakal muncul tulisan exentwo

coba buat

**Comment by ItzKazuki** [comment]
![image](https://github.com/ItzKazuki/School-web/assets/79141593/1fd1d8a1-38af-48dc-95e5-15a0a902887d)
jelek bngt kek ketekuk gitu dia

**Comment by ItzKazuki** [comment]
u liat ga si konten pas di android itu kek kecil banget anjir

**Comment by ItzKazuki** [comment]
ini udh fix ga si buat navbar nya, nanti bikin issue baru dika https://github.com/ItzKazuki/School-web/pull/23

**Comment by 0rcaaa** [comment]
ittu emang cardnya yg setan itu, ntr akalin dh coba, mepet2 ganti konsep

**Comment by 0rcaaa** [comment]
> ini udh fix ga si buat navbar nya, nanti bikin issue baru dika #23

bolehh

**Comment by ItzKazuki** [comment]
> ittu emang cardnya yg setan itu, ntr akalin dh coba, mepet2 ganti konsep

ok la

**Comment by ItzKazuki** [comment]
sip gw merge ya

**Comment by 0rcaaa** [comment]
iy
